name: Run tests

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn

      - name: Build the app
        run: yarn build

      - name: Unit tests
        run: yarn unit-test

      - name: Integrational tests
        run: yarn test

